[package]
name = "atlas"
version.workspace = true
edition.workspace = true

[dependencies]
aether = { version = "0.1.0", path = "../aether" }
anyhow = "1.0.104"
arboard = "3.6.1"
aurora = { version = "0.1.0", path = "../aurora" }
aurora-wgpu = { version = "0.1.0", path = "../aurora-wgpu" }
glam = "0.33.2"
comet = { version = "0.1.0", path = "../comet" }
helios = { version = "0.1.0", path = "../helios" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
photon = { version = "0.1.0", path = "../photon" }
pollster = "1.0.1"
profiling = { version = "1.0.18", features = ["profile-with-puffin"] }
puffin = "0.20.0"
puffin_http = "0.17.0"
ron = "0.12.2"
serde = { version = "1.0.229", features = ["derive"] }
spectrum = { version = "0.1.0", path = "../spectrum" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
winit = "0.30.13"

[dev-dependencies]
slotmap = "1.1.1"
tempfile = "3.27.0"
