//! sandbox - Milestone 1 dev playground: opens a window and draws sprites via photon.

use std::sync::Arc;
use std::time::Instant;

use anyhow::{Context, Result};
use glam::Vec2;
use photon::{Camera, Color, Renderer, Sprite, Texture};
use winit::{
    application::ApplicationHandler,
    event::WindowEvent,
    event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
    window::{Window, WindowId},
};

/// The sample texture, generated by `examples/gen_sprite.rs` and embedded so the
/// binary needs no asset files on disk.
const SPRITE_PNG: &[u8] = include_bytes!("../assets/sprite.png");

fn main() -> Result<()> {
    init_logging();
    tracing::info!("sandbox starting");

    let event_loop = EventLoop::new()?;
    // Redraw continuously - this is a game loop, not an on-demand UI. Vsync
    // (Fifo present mode) paces it to the display's refresh rate.
    event_loop.set_control_flow(ControlFlow::Poll);
    event_loop.run_app(&mut App::default())?;
    Ok(())
}

/// Install a tracing subscriber. Honors the RUST_LOG environment variable;
/// with none set, shows our own info-level logs plus warnings from the noisy
/// wgpu and naga internals. Also captures `log` records from wgpu and winit.
fn init_logging() {
    use tracing_subscriber::{EnvFilter, fmt};
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("info,wgpu_core=warn,wgpu_hal=warn,naga=warn"));
    fmt().with_env_filter(filter).init();
}

#[derive(Default)]
struct App {
    state: Option<State>,
}

struct State {
    window: Arc<Window>,
    renderer: Renderer,
    texture: Texture,
    /// How many sprites to draw; override with the ORBIT_SPRITES env var.
    count: u32,
    /// Wall-clock start, for time-based animation.
    start: Instant,
    /// Reused each frame so the sprite list is not reallocated per frame.
    sprites: Vec<Sprite>,
    /// Frame counter and window start for the once-a-second FPS log.
    frames: u32,
    fps_since: Instant,
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.state.is_some() {
            return;
        }
        match State::new(event_loop) {
            Ok(state) => {
                state.window.request_redraw();
                self.state = Some(state);
            }
            Err(err) => {
                tracing::error!("failed to start sandbox: {err:#}");
                event_loop.exit();
            }
        }
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        let Some(state) = self.state.as_mut() else {
            return;
        };
        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::Resized(size) => state.renderer.resize((size.width, size.height)),
            WindowEvent::RedrawRequested => {
                if let Err(err) = state.draw() {
                    tracing::error!("render error: {err}");
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        if let Some(state) = &self.state {
            state.window.request_redraw();
        }
    }
}

impl State {
    fn new(event_loop: &ActiveEventLoop) -> Result<Self> {
        let attributes = Window::default_attributes().with_title("orbit - sandbox");
        let window = Arc::new(
            event_loop
                .create_window(attributes)
                .context("create window")?,
        );
        let size = window.inner_size();
        let renderer =
            Renderer::new(window.clone(), (size.width, size.height)).context("create renderer")?;

        let decoded = image::load_from_memory(SPRITE_PNG)
            .context("decode sprite.png")?
            .to_rgba8();
        let (w, h) = decoded.dimensions();
        let texture = renderer.create_texture(&decoded.into_raw(), w, h);

        let count = std::env::var("ORBIT_SPRITES")
            .ok()
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(10_000)
            .max(1);
        tracing::info!(
            count,
            "rendering sprite field (override with ORBIT_SPRITES)"
        );

        let now = Instant::now();
        Ok(Self {
            window,
            renderer,
            texture,
            count,
            start: now,
            sprites: Vec::with_capacity(count as usize),
            frames: 0,
            fps_since: now,
        })
    }

    fn draw(&mut self) -> Result<()> {
        let size = self.window.inner_size();
        let viewport = Vec2::new(size.width.max(1) as f32, size.height.max(1) as f32);
        let camera = Camera::new(Vec2::ZERO, viewport);
        let time = self.start.elapsed().as_secs_f32();

        self.build_scene(time, viewport);
        self.renderer.render(
            Color::new(0.02, 0.02, 0.05, 1.0),
            &camera,
            &self.texture,
            &self.sprites,
        )?;
        self.report_fps();
        Ok(())
    }

    /// Rebuild the sprite field for the current time: a grid tiling the
    /// viewport, each sprite gently wobbling, spinning, and cycling hue. All of
    /// them draw in a single instanced call.
    fn build_scene(&mut self, time: f32, viewport: Vec2) {
        let n = self.count;
        let aspect = (viewport.x / viewport.y).max(0.01);
        let cols = ((n as f32 * aspect).sqrt().ceil() as u32).max(1);
        let rows = n.div_ceil(cols).max(1);
        let cell = Vec2::new(viewport.x / cols as f32, viewport.y / rows as f32);
        let size = cell * 0.7;

        self.sprites.clear();
        for i in 0..n {
            let grid = Vec2::new((i % cols) as f32, (i / cols) as f32);
            let center = (grid + 0.5) * cell;
            let phase = i as f32 * 0.35;
            let wobble =
                Vec2::new((time * 1.7 + phase).sin(), (time * 2.1 + phase).cos()) * (cell * 0.18);

            let mut sprite = Sprite::new(center + wobble - size * 0.5, size);
            sprite.rotation = time * 0.6 + phase;
            sprite.tint = Color::hsv((i as f32 / n as f32) + time * 0.05, 0.7, 1.0);
            self.sprites.push(sprite);
        }
    }

    /// Log frames-per-second and frame time once a second.
    fn report_fps(&mut self) {
        self.frames += 1;
        let elapsed = self.fps_since.elapsed().as_secs_f32();
        if elapsed >= 1.0 {
            let fps = self.frames as f32 / elapsed;
            tracing::info!(
                sprites = self.count,
                "{} fps ({:.2} ms/frame)",
                fps as u32,
                1000.0 / fps
            );
            self.frames = 0;
            self.fps_since = Instant::now();
        }
    }
}
