//! sandbox - Milestone 1 dev playground: opens a window and draws sprites via photon.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use anyhow::{Context, Result};
use glam::Vec2;
use photon::{Camera, Color, Renderer, Sprite, Texture};
use winit::{
    application::ApplicationHandler,
    event::WindowEvent,
    event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
    window::{Window, WindowId},
};

/// The sample texture, generated by `examples/gen_sprite.rs` and embedded so the
/// binary needs no asset files on disk.
const SPRITE_PNG: &[u8] = include_bytes!("../assets/sprite.png");

fn main() -> Result<()> {
    init_logging();
    tracing::info!("sandbox starting");

    // Kept alive for the whole run; dropping it would stop the profiler server.
    let _profiler = init_profiling();

    let event_loop = EventLoop::new()?;
    // Redraw continuously - this is a game loop, not an on-demand UI. Vsync
    // (Fifo present mode) paces it to the display's refresh rate.
    event_loop.set_control_flow(ControlFlow::Poll);
    event_loop.run_app(&mut App::default())?;
    Ok(())
}

/// Install a tracing subscriber. Honors the RUST_LOG environment variable;
/// with none set, shows our own info-level logs plus warnings from the noisy
/// wgpu and naga internals. Also captures `log` records from wgpu and winit.
fn init_logging() {
    use tracing_subscriber::{EnvFilter, fmt};
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("info,wgpu_core=warn,wgpu_hal=warn,naga=warn"));
    fmt().with_env_filter(filter).init();
}

/// Start the puffin profiler server when ORBIT_PROFILE is set, and return it so
/// the caller keeps it alive. When unset, profiling stays off and the
/// `profiling::scope!` calls throughout photon and the sandbox are cheap
/// no-ops. Connect a viewer with `puffin_viewer --url 127.0.0.1:8585`.
fn init_profiling() -> Option<puffin_http::Server> {
    // Off unless ORBIT_PROFILE is set; `?` early-returns None when it is absent.
    std::env::var_os("ORBIT_PROFILE")?;
    puffin::set_scopes_on(true);
    match puffin_http::Server::new("0.0.0.0:8585") {
        Ok(server) => {
            tracing::info!("puffin profiler on; connect with: puffin_viewer --url 127.0.0.1:8585");
            Some(server)
        }
        Err(err) => {
            tracing::error!("failed to start puffin server: {err}");
            None
        }
    }
}

#[derive(Default)]
struct App {
    state: Option<State>,
}

struct State {
    window: Arc<Window>,
    renderer: Renderer,
    texture: Texture,
    /// How many sprites to draw; override with the ORBIT_SPRITES env var.
    count: u32,
    /// Wall-clock start, for time-based animation.
    start: Instant,
    /// Reused each frame so the sprite list is not reallocated per frame.
    sprites: Vec<Sprite>,
    /// Frame counter and window start for the once-a-second FPS log.
    frames: u32,
    fps_since: Instant,
    /// A puffin frame sink for the readable profile dump; present only when
    /// profiling is on. Paired with `dump_path` from ORBIT_PROFILE_DUMP.
    frame_view: Option<puffin::GlobalFrameView>,
    dump_path: Option<PathBuf>,
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.state.is_some() {
            return;
        }
        match State::new(event_loop) {
            Ok(state) => {
                state.window.request_redraw();
                self.state = Some(state);
            }
            Err(err) => {
                tracing::error!("failed to start sandbox: {err:#}");
                event_loop.exit();
            }
        }
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        let Some(state) = self.state.as_mut() else {
            return;
        };
        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::Resized(size) => state.renderer.resize((size.width, size.height)),
            WindowEvent::RedrawRequested => {
                if let Err(err) = state.draw() {
                    tracing::error!("render error: {err}");
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        if let Some(state) = &self.state {
            state.window.request_redraw();
        }
    }
}

impl State {
    fn new(event_loop: &ActiveEventLoop) -> Result<Self> {
        let attributes = Window::default_attributes().with_title("orbit - sandbox");
        let window = Arc::new(
            event_loop
                .create_window(attributes)
                .context("create window")?,
        );
        let size = window.inner_size();
        let renderer =
            Renderer::new(window.clone(), (size.width, size.height)).context("create renderer")?;

        let decoded = image::load_from_memory(SPRITE_PNG)
            .context("decode sprite.png")?
            .to_rgba8();
        let (w, h) = decoded.dimensions();
        let texture = renderer.create_texture(&decoded.into_raw(), w, h);

        let count = std::env::var("ORBIT_SPRITES")
            .ok()
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(10_000)
            .max(1);
        tracing::info!(
            count,
            "rendering sprite field (override with ORBIT_SPRITES)"
        );

        let dump_path = std::env::var_os("ORBIT_PROFILE_DUMP").map(PathBuf::from);
        let frame_view = puffin::are_scopes_on().then(puffin::GlobalFrameView::default);
        match (&dump_path, frame_view.is_some()) {
            (Some(path), true) => {
                tracing::info!(
                    "writing a readable profile to {} each second",
                    path.display()
                )
            }
            (Some(_), false) => tracing::warn!(
                "ORBIT_PROFILE_DUMP is set but profiling is off; also set ORBIT_PROFILE=1"
            ),
            _ => {}
        }

        let now = Instant::now();
        Ok(Self {
            window,
            renderer,
            texture,
            count,
            start: now,
            sprites: Vec::with_capacity(count as usize),
            frames: 0,
            fps_since: now,
            frame_view,
            dump_path,
        })
    }

    fn draw(&mut self) -> Result<()> {
        let size = self.window.inner_size();
        let viewport = Vec2::new(size.width.max(1) as f32, size.height.max(1) as f32);
        let camera = Camera::new(Vec2::ZERO, viewport);
        let time = self.start.elapsed().as_secs_f32();

        self.build_scene(time, viewport);
        self.renderer.render(
            Color::new(0.02, 0.02, 0.05, 1.0),
            &camera,
            &self.texture,
            &self.sprites,
        )?;
        self.report_fps();

        // Mark the frame boundary for the profiler (a no-op when profiling off).
        profiling::finish_frame!();
        Ok(())
    }

    /// Rebuild the sprite field for the current time: a grid tiling the
    /// viewport, each sprite gently wobbling, spinning, and cycling hue. All of
    /// them draw in a single instanced call.
    fn build_scene(&mut self, time: f32, viewport: Vec2) {
        profiling::scope!("build_scene");
        let n = self.count;
        let aspect = (viewport.x / viewport.y).max(0.01);
        let cols = ((n as f32 * aspect).sqrt().ceil() as u32).max(1);
        let rows = n.div_ceil(cols).max(1);
        let cell = Vec2::new(viewport.x / cols as f32, viewport.y / rows as f32);
        let size = cell * 0.7;

        self.sprites.clear();
        for i in 0..n {
            let grid = Vec2::new((i % cols) as f32, (i / cols) as f32);
            let center = (grid + 0.5) * cell;
            let phase = i as f32 * 0.35;
            let wobble =
                Vec2::new((time * 1.7 + phase).sin(), (time * 2.1 + phase).cos()) * (cell * 0.18);

            let mut sprite = Sprite::new(center + wobble - size * 0.5, size);
            sprite.rotation = time * 0.6 + phase;
            sprite.tint = Color::hsv((i as f32 / n as f32) + time * 0.05, 0.7, 1.0);
            self.sprites.push(sprite);
        }
    }

    /// Log frames-per-second and frame time once a second.
    fn report_fps(&mut self) {
        self.frames += 1;
        let elapsed = self.fps_since.elapsed().as_secs_f32();
        if elapsed >= 1.0 {
            let fps = self.frames as f32 / elapsed;
            tracing::info!(
                sprites = self.count,
                "{} fps ({:.2} ms/frame)",
                fps as u32,
                1000.0 / fps
            );
            self.dump_profile();
            self.frames = 0;
            self.fps_since = Instant::now();
        }
    }

    /// Write the merged per-scope timings of recent frames to `dump_path` as
    /// readable text. No-op unless both profiling and ORBIT_PROFILE_DUMP are on.
    fn dump_profile(&self) {
        let (Some(view), Some(path)) = (&self.frame_view, &self.dump_path) else {
            return;
        };
        let view = view.lock();
        let frames: Vec<_> = view
            .latest_frames(120)
            .filter_map(|f| f.unpacked().ok())
            .collect();
        let Some(latest) = frames.last() else {
            return;
        };

        let mut out = format!(
            "orbit profile - {} sprites, merged over {} frames (per-frame averages)\n",
            self.count,
            frames.len(),
        );
        let scopes = view.scope_collection();
        for thread in latest.thread_streams.keys() {
            out.push_str(&format!("\n[thread: {}]\n", thread.name));
            match puffin::merge_scopes_for_thread(scopes, &frames, thread) {
                Ok(merged) => {
                    for scope in &merged {
                        Self::format_scope(&mut out, scopes, scope, 1);
                    }
                }
                Err(err) => out.push_str(&format!("  merge failed: {err:?}\n")),
            }
        }

        if let Err(err) = std::fs::write(path, out) {
            tracing::error!("failed to write profile dump to {}: {err}", path.display());
        }
    }

    /// Format one merged scope and its children as an indented line.
    fn format_scope(
        out: &mut String,
        scopes: &puffin::ScopeCollection,
        scope: &puffin::MergeScope<'_>,
        depth: usize,
    ) {
        let name = scopes
            .fetch_by_id(&scope.id)
            .map(|d| d.scope_name.as_deref().unwrap_or(d.function_name.as_ref()))
            .unwrap_or("?");
        let per_frame_ms = scope.duration_per_frame_ns as f64 / 1e6;
        let max_ms = scope.max_duration_ns as f64 / 1e6;
        let indent = depth * 2;
        out.push_str(&format!(
            "{:indent$}{name}  {per_frame_ms:.3} ms/frame  (max {max_ms:.3} ms, {} calls)\n",
            "", scope.num_pieces,
        ));
        for child in &scope.children {
            Self::format_scope(out, scopes, child, depth + 1);
        }
    }
}
