//! sandbox - Milestone 1 dev playground: opens a window and draws sprites via photon.

use std::sync::Arc;

use anyhow::{Context, Result};
use glam::Vec2;
use photon::{Camera, Color, Renderer, Sprite, Texture};
use winit::{
    application::ApplicationHandler,
    event::WindowEvent,
    event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
    window::{Window, WindowId},
};

/// The sample texture, generated by `examples/gen_sprite.rs` and embedded so the
/// binary needs no asset files on disk.
const SPRITE_PNG: &[u8] = include_bytes!("../assets/sprite.png");

fn main() -> Result<()> {
    let event_loop = EventLoop::new()?;
    // Redraw continuously - this is a game loop, not an on-demand UI. Vsync
    // (Fifo present mode) paces it to the display's refresh rate.
    event_loop.set_control_flow(ControlFlow::Poll);
    event_loop.run_app(&mut App::default())?;
    Ok(())
}

#[derive(Default)]
struct App {
    state: Option<State>,
}

struct State {
    window: Arc<Window>,
    renderer: Renderer,
    texture: Texture,
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.state.is_some() {
            return;
        }
        match State::new(event_loop) {
            Ok(state) => {
                state.window.request_redraw();
                self.state = Some(state);
            }
            Err(err) => {
                eprintln!("failed to start sandbox: {err:#}");
                event_loop.exit();
            }
        }
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        let Some(state) = self.state.as_mut() else {
            return;
        };
        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::Resized(size) => state.renderer.resize((size.width, size.height)),
            WindowEvent::RedrawRequested => {
                if let Err(err) = state.draw() {
                    eprintln!("render error: {err}");
                }
            }
            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        if let Some(state) = &self.state {
            state.window.request_redraw();
        }
    }
}

impl State {
    fn new(event_loop: &ActiveEventLoop) -> Result<Self> {
        let attributes = Window::default_attributes().with_title("orbit - sandbox");
        let window = Arc::new(
            event_loop
                .create_window(attributes)
                .context("create window")?,
        );
        let size = window.inner_size();
        let renderer =
            Renderer::new(window.clone(), (size.width, size.height)).context("create renderer")?;

        let decoded = image::load_from_memory(SPRITE_PNG)
            .context("decode sprite.png")?
            .to_rgba8();
        let (w, h) = decoded.dimensions();
        let texture = renderer.create_texture(&decoded.into_raw(), w, h);

        Ok(Self {
            window,
            renderer,
            texture,
        })
    }

    fn draw(&mut self) -> Result<()> {
        let size = self.window.inner_size();
        let viewport = Vec2::new(size.width as f32, size.height as f32);
        let camera = Camera::new(Vec2::ZERO, viewport);

        // One sprite centered at full size, plus a half-size one in each of the
        // top-left and bottom-right corners - enough to read position and scale.
        let tex = Vec2::new(self.texture.width as f32, self.texture.height as f32);
        let sprites = [
            Sprite::new(viewport / 2.0 - tex / 2.0, tex),
            Sprite::new(Vec2::new(20.0, 20.0), tex * 0.5),
            Sprite::new(viewport - Vec2::splat(20.0) - tex * 0.5, tex * 0.5),
        ];

        self.renderer.render(
            Color::new(0.10, 0.10, 0.12, 1.0),
            &camera,
            &self.texture,
            &sprites,
        )?;
        Ok(())
    }
}
